/**
 ********************************************************************************
 * Copyright (c) 2016-2019 Vector Informatik GmbH and others.
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *     Vector Informatik GmbH - initial API and implementation
 ********************************************************************************
 */
package org.eclipse.app4mc.amalthea.validations.ta.basic;

import java.util.List;

import org.eclipse.app4mc.amalthea.model.AmaltheaServices;
import org.eclipse.app4mc.amalthea.model.ContinuousValueInterval;
import org.eclipse.app4mc.amalthea.model.INamed;
import org.eclipse.app4mc.amalthea.validation.core.AmaltheaValidation;
import org.eclipse.app4mc.validation.annotation.Validation;
import org.eclipse.app4mc.validation.core.ValidationDiagnostic;
import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EObject;

/**
 * Checks sanity of lower and upper bound of continuous value intervals
 * 
 * <ul>
 * <li>upper bounds must be greater than or equal to lower bounds</li>
 * </ul>
 */

@Validation(id = "TA-Basic-ContinuousValueInterval-LowerUpper")
public class TABasicContinuousValueInterval extends AmaltheaValidation {

	@Override
	public EClassifier getEClassifier() {
		return ePackage.getContinuousValueInterval();
	}

	@Override
	public void validate(EObject eObject, List<ValidationDiagnostic> results) {
		if (eObject instanceof ContinuousValueInterval) {
			ContinuousValueInterval cvi = (ContinuousValueInterval) eObject;
			INamed namedContainer = AmaltheaServices.getContainerOfType(cvi, INamed.class);
			Double lower = cvi.getLowerBound();
			Double upper = cvi.getUpperBound();
			// if lower or upper are null the error will be generated by the intrinsic emf check
			if (lower != null && !lower.isNaN() && !lower.isInfinite() && upper != null && !upper.isNaN() && !upper.isInfinite()) {
				if (lower.compareTo(upper) > 0) {
					addIssue(results, cvi, ePackage.getContinuousValueInterval_LowerBound(),
							getEClassifier().getName() + ": lower bound is higher than the upper: (" + lower + " > " + upper + ", in " + objectInfo(namedContainer) + ")");
				}
			}
		}
	}

}
